<?php

return [
    'core' => [
        // Contracts file
        base_path('vendor/illuminate/contracts/Container/Container.php'),
        base_path('vendor/illuminate/contracts/Container/ContextualBindingBuilder.php'),
        base_path('vendor/illuminate/contracts/Foundation/Application.php'),
        base_path('vendor/illuminate/contracts/Bus/Dispatcher.php'),
        base_path('vendor/illuminate/contracts/Bus/QueueingDispatcher.php'),
        base_path('vendor/illuminate/contracts/Pipeline/Pipeline.php'),
        base_path('vendor/illuminate/contracts/Support/Renderable.php'),
        base_path('vendor/illuminate/contracts/Logging/Log.php'),
        base_path('vendor/illuminate/contracts/Debug/ExceptionHandler.php'),
        base_path('vendor/illuminate/contracts/Config/Repository.php'),
        base_path('vendor/illuminate/contracts/Events/Dispatcher.php'),
        base_path('vendor/illuminate/contracts/Support/Arrayable.php'),
        base_path('vendor/illuminate/contracts/Support/Jsonable.php'),
        base_path('vendor/illuminate/contracts/Cookie/Factory.php'),
        base_path('vendor/illuminate/contracts/Cookie/QueueingFactory.php'),
        base_path('vendor/illuminate/contracts/Encryption/Encrypter.php'),
        base_path('vendor/illuminate/contracts/Queue/QueueableEntity.php'),
        base_path('vendor/illuminate/contracts/Routing/Registrar.php'),
        base_path('vendor/illuminate/contracts/Routing/ResponseFactory.php'),
        base_path('vendor/illuminate/contracts/Routing/UrlGenerator.php'),
        base_path('vendor/illuminate/contracts/Routing/UrlRoutable.php'),
        base_path('vendor/illuminate/contracts/Validation/ValidatesWhenResolved.php'),
        base_path('vendor/illuminate/contracts/View/Factory.php'),
        base_path('vendor/illuminate/contracts/Support/MessageProvider.php'),
        base_path('vendor/illuminate/contracts/Support/MessageBag.php'),
        base_path('vendor/illuminate/contracts/View/View.php'),
        base_path('vendor/illuminate/contracts/Http/Kernel.php'),
        base_path('vendor/illuminate/contracts/Auth/Guard.php'),
        base_path('vendor/illuminate/contracts/Auth/StatefulGuard.php'),
        base_path('vendor/illuminate/contracts/Auth/Access/Gate.php'),
        base_path('vendor/illuminate/contracts/Hashing/Hasher.php'),
        base_path('vendor/illuminate/contracts/Auth/UserProvider.php'),
        base_path('vendor/illuminate/contracts/Pagination/Paginator.php'),

        // Auth
        base_path('vendor/illuminate/auth/AuthManager.php'),
        base_path('vendor/illuminate/auth/SessionGuard.php'),
        base_path('vendor/illuminate/auth/Access/Gate.php'),
        base_path('vendor/illuminate/auth/EloquentUserProvider.php'),
        base_path('vendor/illuminate/auth/AuthServiceProvider.php'),

        // Container
        base_path('vendor/illuminate/container/Container.php'),

        // Symfony Http Kernel
        base_path('vendor/symfony/http-kernel/HttpKernelInterface.php'),
        base_path('vendor/symfony/http-kernel/TerminableInterface.php'),

        // Laravel Http
        base_path('vendor/illuminate/http/ResponseTrait.php'),
        base_path('vendor/illuminate/http/Response.php'),
        base_path('vendor/illuminate/http/Middleware/FrameGuard.php'),

        // Symfony Http Foundation
        base_path('vendor/symfony/http-foundation/ParameterBag.php'),
        base_path('vendor/symfony/http-foundation/FileBag.php'),
        base_path('vendor/symfony/http-foundation/ServerBag.php'),
        base_path('vendor/symfony/http-foundation/HeaderBag.php'),
        base_path('vendor/symfony/http-foundation/Session/SessionInterface.php'),
        base_path('vendor/symfony/http-foundation/Session/SessionBagInterface.php'),
        base_path('vendor/symfony/http-foundation/Session/Attribute/AttributeBagInterface.php'),
        base_path('vendor/symfony/http-foundation/Session/Attribute/AttributeBag.php'),
        base_path('vendor/symfony/http-foundation/Session/Storage/MetadataBag.php'),
        base_path('vendor/symfony/http-foundation/AcceptHeaderItem.php'),
        base_path('vendor/symfony/http-foundation/AcceptHeader.php'),
        base_path('vendor/symfony/http-foundation/Response.php'),
        base_path('vendor/symfony/http-foundation/ResponseHeaderBag.php'),
        base_path('vendor/symfony/http-foundation/Cookie.php'),

        // Laravel Support
        base_path('vendor/illuminate/support/ServiceProvider.php'),
        base_path('vendor/illuminate/support/AggregateServiceProvider.php'),
        base_path('vendor/illuminate/support/Facades/Facade.php'),
        base_path('vendor/illuminate/support/Traits/Macroable.php'),
        base_path('vendor/illuminate/support/Arr.php'),
        base_path('vendor/illuminate/support/Str.php'),
        base_path('vendor/illuminate/support/NamespacedItemResolver.php'),
        base_path('vendor/illuminate/support/Facades/App.php'),
        base_path('vendor/illuminate/support/Facades/Route.php'),
        base_path('vendor/illuminate/support/ViewErrorBag.php'),
        base_path('vendor/illuminate/support/MessageBag.php'),
        base_path('vendor/illuminate/support/Facades/View.php'),
        base_path('vendor/illuminate/support/Manager.php'),
        base_path('vendor/illuminate/support/Collection.php'),
        base_path('vendor/illuminate/support/Facades/Log.php'),

        // Laravel Events
        base_path('vendor/illuminate/events/Dispatcher.php'),
        base_path('vendor/illuminate/events/EventServiceProvider.php'),

        // Laravel Validation
        base_path('vendor/illuminate/validation/Validator.php'),
        base_path('vendor/illuminate/validation/ValidationServiceProvider.php'),
        base_path('vendor/illuminate/validation/DatabasePresenceVerifier.php'),
        base_path('vendor/illuminate/validation/Factory.php'),
        base_path('vendor/illuminate/validation/ValidatesWhenResolvedTrait.php'),
        base_path('vendor/illuminate/validation/PresenceVerifierInterface.php'),
        base_path('vendor/illuminate/validation/ValidationException.php'),

        // Laravel Pagination
        base_path('vendor/illuminate/pagination/AbstractPaginator.php'),
        base_path('vendor/illuminate/pagination/Paginator.php'),
        base_path('vendor/illuminate/pagination/PaginationServiceProvider.php'),

        // Laravel Hashing
        base_path('vendor/illuminate/hashing/HashServiceProvider.php'),
        base_path('vendor/illuminate/hashing/BcryptHasher.php'),

        // Laravel Configurator
        base_path('vendor/illuminate/config/Repository.php'),

        // Laravel Filesystem
        base_path('vendor/illuminate/filesystem/Filesystem.php'),
        base_path('vendor/illuminate/filesystem/FilesystemServiceProvider.php'),

        // Laravel Pipeline
        base_path('vendor/illuminate/pipeline/Pipeline.php'),

        // Laravel Database
        base_path('vendor/illuminate/database/Connection.php'),
        base_path('vendor/illuminate/database/Grammar.php'),
        base_path('vendor/illuminate/database/DatabaseManager.php'),
        base_path('vendor/illuminate/database/PostgresConnection.php'),
        base_path('vendor/illuminate/database/Query/Grammars/Grammar.php'),
        base_path('vendor/illuminate/database/Query/Grammars/SqlServerGrammar.php'),
        base_path('vendor/illuminate/database/Query/Grammars/MySqlGrammar.php'),
        base_path('vendor/illuminate/database/Query/Grammars/PostgresGrammar.php'),
        base_path('vendor/illuminate/database/Query/Grammars/SQLiteGrammar.php'),
        base_path('vendor/illuminate/database/Query/Expression.php'),
        base_path('vendor/illuminate/database/Query/Processors/SQLiteProcessor.php'),
        base_path('vendor/illuminate/database/Query/Processors/Processor.php'),
        base_path('vendor/illuminate/database/Query/Processors/SqlServerProcessor.php'),
        base_path('vendor/illuminate/database/Query/Processors/PostgresProcessor.php'),
        base_path('vendor/illuminate/database/Query/Processors/MySqlProcessor.php'),
        base_path('vendor/illuminate/database/Query/JoinClause.php'),
        base_path('vendor/illuminate/database/ConnectionInterface.php'),
        base_path('vendor/illuminate/database/SQLiteConnection.php'),
        base_path('vendor/illuminate/database/Connectors/ConnectionFactory.php'),
        base_path('vendor/illuminate/database/Connectors/SqlServerConnector.php'),
        base_path('vendor/illuminate/database/Connectors/PostgresConnector.php'),
        base_path('vendor/illuminate/database/Connectors/ConnectorInterface.php'),
        base_path('vendor/illuminate/database/Connectors/MySqlConnector.php'),
        base_path('vendor/illuminate/database/Connectors/SQLiteConnector.php'),
        base_path('vendor/illuminate/database/MySqlConnection.php'),
        base_path('vendor/illuminate/database/DatabaseServiceProvider.php'),
        base_path('vendor/illuminate/database/Events/ConnectionEvent.php'),
        base_path('vendor/illuminate/database/Events/TransactionCommitted.php'),
        base_path('vendor/illuminate/database/Events/TransactionBeginning.php'),
        base_path('vendor/illuminate/database/Events/TransactionRolledBack.php'),
        base_path('vendor/illuminate/database/Events/QueryExecuted.php'),
        base_path('vendor/illuminate/database/Migrations/Migrator.php'),
        base_path('vendor/illuminate/database/Migrations/Migration.php'),
        base_path('vendor/illuminate/database/Migrations/MigrationCreator.php'),
        base_path('vendor/illuminate/database/Migrations/MigrationRepositoryInterface.php'),
        base_path('vendor/illuminate/database/Migrations/DatabaseMigrationRepository.php'),
        base_path('vendor/illuminate/database/Schema/Blueprint.php'),
        base_path('vendor/illuminate/database/Schema/Grammars/Grammar.php'),
        base_path('vendor/illuminate/database/Schema/Grammars/SqlServerGrammar.php'),
        base_path('vendor/illuminate/database/Schema/Grammars/MySqlGrammar.php'),
        base_path('vendor/illuminate/database/Schema/Grammars/PostgresGrammar.php'),
        base_path('vendor/illuminate/database/Schema/Grammars/SQLiteGrammar.php'),
        base_path('vendor/illuminate/database/Schema/MySqlBuilder.php'),
        base_path('vendor/illuminate/database/Schema/PostgresBuilder.php'),
        base_path('vendor/illuminate/database/ConnectionResolverInterface.php'),
        base_path('vendor/illuminate/database/Capsule/Manager.php'),
        base_path('vendor/illuminate/database/SqlServerConnection.php'),
        base_path('vendor/illuminate/database/Eloquent/FactoryBuilder.php'),
        base_path('vendor/illuminate/database/Eloquent/Relations/MorphTo.php'),
        base_path('vendor/illuminate/database/Eloquent/Relations/HasManyThrough.php'),
        base_path('vendor/illuminate/database/Eloquent/Relations/Relation.php'),
        base_path('vendor/illuminate/database/Eloquent/Relations/HasOneOrMany.php'),
        base_path('vendor/illuminate/database/Eloquent/Relations/MorphMany.php'),
        base_path('vendor/illuminate/database/Eloquent/Relations/Pivot.php'),
        base_path('vendor/illuminate/database/Eloquent/Relations/MorphOne.php'),
        base_path('vendor/illuminate/database/Eloquent/Relations/HasMany.php'),
        base_path('vendor/illuminate/database/Eloquent/Relations/MorphToMany.php'),
        base_path('vendor/illuminate/database/Eloquent/Relations/MorphOneOrMany.php'),
        base_path('vendor/illuminate/database/Eloquent/Relations/MorphPivot.php'),
        base_path('vendor/illuminate/database/Eloquent/Relations/HasOne.php'),
        base_path('vendor/illuminate/database/Eloquent/Relations/BelongsTo.php'),
        base_path('vendor/illuminate/database/Eloquent/Relations/BelongsToMany.php'),
        base_path('vendor/illuminate/database/Eloquent/SoftDeletingScope.php'),
        base_path('vendor/illuminate/database/Eloquent/ModelNotFoundException.php'),
        base_path('vendor/illuminate/database/Eloquent/Factory.php'),
        base_path('vendor/illuminate/database/Eloquent/QueueEntityResolver.php'),
        base_path('vendor/illuminate/database/Eloquent/SoftDeletes.php'),
        base_path('vendor/illuminate/database/Eloquent/MassAssignmentException.php'),
        base_path('vendor/illuminate/database/Eloquent/Scope.php'),
        base_path('vendor/illuminate/database/Eloquent/Collection.php'),
        base_path('vendor/illuminate/database/Eloquent/ScopeInterface.php'),
        base_path('vendor/illuminate/database/Console/Migrations/BaseCommand.php'),
        base_path('vendor/illuminate/database/Console/Migrations/RefreshCommand.php'),
        base_path('vendor/illuminate/database/Console/Migrations/MigrateCommand.php'),
        base_path('vendor/illuminate/database/Console/Migrations/RollbackCommand.php'),
        base_path('vendor/illuminate/database/Console/Migrations/StatusCommand.php'),
        base_path('vendor/illuminate/database/Console/Migrations/MigrateMakeCommand.php'),
        base_path('vendor/illuminate/database/Console/Migrations/ResetCommand.php'),
        base_path('vendor/illuminate/database/Console/Migrations/InstallCommand.php'),
        base_path('vendor/illuminate/database/DetectsLostConnections.php'),
        base_path('vendor/illuminate/database/MigrationServiceProvider.php'),
        base_path('vendor/illuminate/database/QueryException.php'),
        base_path('vendor/illuminate/database/ConnectionResolver.php'),

        // Laravel Encryption
        base_path('vendor/illuminate/encryption/BaseEncrypter.php'),
        base_path('vendor/illuminate/encryption/Encrypter.php'),
        base_path('vendor/illuminate/encryption/EncryptionServiceProvider.php'),

        // Psr Log
        base_path('vendor/psr/log/Psr/Log/LoggerInterface.php'),

        // Monolog
        base_path('vendor/monolog/monolog/src/Monolog/Logger.php'),
        base_path('vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php'),
        base_path('vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php'),
        base_path('vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php'),
        base_path('vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php'),
        base_path('vendor/monolog/monolog/src/Monolog/Handler/HandlerInterface.php'),
        base_path('vendor/monolog/monolog/src/Monolog/Formatter/FormatterInterface.php'),
        base_path('vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php'),
        base_path('vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php'),

        // Symfony Finder
        base_path('vendor/symfony/finder/SplFileInfo.php'),
        base_path('vendor/symfony/finder/Iterator/FilterIterator.php'),
        base_path('vendor/symfony/finder/Iterator/MultiplePcreFilterIterator.php'),
        base_path('vendor/symfony/finder/Iterator/PathFilterIterator.php'),
        base_path('vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php'),
        base_path('vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php'),
        base_path('vendor/symfony/finder/Iterator/FileTypeFilterIterator.php'),
        base_path('vendor/symfony/finder/Iterator/FilenameFilterIterator.php'),
        base_path('vendor/symfony/finder/Finder.php'),
        base_path('vendor/symfony/finder/Glob.php'),

        // DotEnv
        base_path('vendor/vlucas/phpdotenv/src/Dotenv.php'),

        // Carbon
        base_path('vendor/nesbot/carbon/src/Carbon/Carbon.php'),

        // Fast Route
        base_path('vendor/nikic/fast-route/src/RouteParser/Std.php'),
        base_path('vendor/nikic/fast-route/src/BadRouteException.php'),
        base_path('vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php'),
        base_path('vendor/nikic/fast-route/src/DataGenerator/MarkBased.php'),
        base_path('vendor/nikic/fast-route/src/DataGenerator/GroupPosBased.php'),
        base_path('vendor/nikic/fast-route/src/DataGenerator/GroupCountBased.php'),
        base_path('vendor/nikic/fast-route/src/DataGenerator/CharCountBased.php'),
        base_path('vendor/nikic/fast-route/src/RouteCollector.php'),
        base_path('vendor/nikic/fast-route/src/Route.php'),
        base_path('vendor/nikic/fast-route/src/bootstrap.php'),
        base_path('vendor/nikic/fast-route/src/DataGenerator.php'),
        base_path('vendor/nikic/fast-route/src/RouteParser.php'),
        base_path('vendor/nikic/fast-route/src/Dispatcher.php'),
        base_path('vendor/nikic/fast-route/src/Dispatcher/RegexBasedAbstract.php'),
        base_path('vendor/nikic/fast-route/src/Dispatcher/MarkBased.php'),
        base_path('vendor/nikic/fast-route/src/Dispatcher/GroupPosBased.php'),
        base_path('vendor/nikic/fast-route/src/Dispatcher/GroupCountBased.php'),
        base_path('vendor/nikic/fast-route/src/Dispatcher/CharCountBased.php'),
        base_path('vendor/nikic/fast-route/src/functions.php'),

        // Lumen
        base_path('vendor/laravel/lumen-framework/Concerns/RegistersExceptionHandlers.php'),
        base_path('vendor/laravel/lumen-framework/Concerns/RoutesRequests.php'),
        base_path('vendor/laravel/lumen-framework/Providers/EventServiceProvider.php'),
        base_path('vendor/laravel/lumen-framework/Exceptions/Handler.php'),
        base_path('vendor/laravel/lumen-framework/Auth/Authorizable.php'),
        base_path('vendor/laravel/lumen-framework/Routing/Pipeline.php'),
        base_path('vendor/laravel/lumen-framework/Routing/Closure.php'),
        base_path('vendor/laravel/lumen-framework/Routing/Controller.php'),
        base_path('vendor/laravel/lumen-framework/Routing/ProvidesConvenienceMethods.php'),
        base_path('vendor/laravel/lumen-framework/Routing/UrlGenerator.php'),
        base_path('vendor/laravel/lumen-framework/Console/Kernel.php'),
        base_path('vendor/laravel/lumen-framework/helpers.php'),
        base_path('vendor/laravel/lumen-framework/Application.php'),
        base_path('vendor/laravel/lumen-framework/Http/ResponseFactory.php'),
        base_path('vendor/laravel/lumen-framework/Http/Redirector.php'),
    ],
];
